# shellcheck shell=bash
#
# lib/panel/node/install.sh — Remote Node: полный orchestration-flow
# (Stage 7, STEP 2 деплой + STEP 3 регистрация/health-check).
#
# Запускается С Panel-хоста, отдельным пунктом меню, ПОСЛЕ того как Panel
# уже установлена (нужны существующие SUPERADMIN_USER/PASS для входа в
# Panel API — они не хранятся server-manager'ом между сессиями, поэтому
# запрашиваются здесь заново).
#
# Переиспользует без изменений: ask_ssh_target, init_ssh_helpers,
# check_ssh_connection, RUN, PUT (lib/common/ssh.sh); remote_install_deps
# (вариант "node"); ask, validate_domain, confirm, get_public_ip
# (lib/common/*); panel_generate_node_compose (lib/panel/node/compose.sh,
# STEP 1, не изменялся); panel_generate_selfsteal_site (lib/panel/selfsteal.sh,
# параметризован опциональным output-dir); panel_node_fetch_secret,
# panel_node_register, panel_node_wait_connected (lib/panel/node/api.sh).
#
# Firewall-инвариант: 2222/tcp на ноде открыт ТОЛЬКО с адреса Panel
# (PANEL_IP) — никогда 0.0.0.0/0. get_public_ip() предлагается как
# редактируемый default, не как единственный источник (см. предыдущие
# раунды исследования — автоопределение не считается надёжным сам по себе).

panel_install_remote_node() {
    header "Remote Node — установка"
    echo ""
    warn "Panel должна быть уже установлена — потребуются её admin-credentials."
    warn "Повторный запуск создаст новую ноду/хост в Panel (операция не идемпотентна)."
    echo ""

    local _selfsteal_staging=""
    local _node_cleanup_done=""

    # F1 (SSH reliability): single cleanup function, all traps delegate to
    # it instead of duplicating the `rm -rf` logic. Idempotent — safe to
    # call more than once (RETURN *and* an INT/TERM path can both reach
    # it) and safe if nothing was created yet (both paths are plain `rm
    # -rf`, which no-ops on a non-existent target). Removes only the two
    # local paths this flow itself creates.
    _node_install_cleanup() {
        # NOTE: guarded with `if`, not `[ ... ] && return 0` -- this whole
        # tool runs under `set -euo pipefail` (server-manager.sh:13). A
        # bare `cond && action` used as a full statement evaluates to the
        # condition's own truth value when the condition is false, and
        # under `set -e` a false statement at this level aborts the
        # *entire function* right there -- which, for a RETURN trap that
        # runs on every ordinary exit path, would have made this trap
        # non-functional on its very first (expected, false-condition)
        # call. Confirmed by testing under `set -euo pipefail` this
        # session; `if`/`fi` is not stylistic here, it is required.
        if [ -n "${_node_cleanup_done:-}" ]; then
            return 0
        fi
        _node_cleanup_done=1
        rm -rf /opt/remnanode "$_selfsteal_staging" 2>/dev/null
    }

    # F1: a RETURN trap does NOT fire when the function is killed by an
    # uncaught signal — confirmed empirically (RETURN only runs when a
    # shell function actually finishes executing; a process terminated by
    # a signal never reaches that bookkeeping). INT/TERM therefore need
    # their own explicit handler; they must not rely on RETURN.
    _node_install_signal_cleanup() {
        local _sig="$1"

        # Best-effort: kill the in-flight RUN/PUT subtree, if any. Right
        # after `timeout ... &`, RUN/PUT's own $! *is* the PGID of a fresh
        # process group timeout creates for itself (GNU timeout's default,
        # non---foreground mode: it calls setpgid(0,0) precisely so it can
        # reliably signal its whole descendant tree on its own deadline —
        # confirmed empirically this session, including that sshpass
        # interposes at least one further process before reaching the
        # real ssh/scp binary, which is exactly why signaling only the
        # direct child would not be enough). `-"$_LAST_SSH_PID"` reaches
        # the whole tree in one signal.
        # `if`, not `[ ... ] && kill ...`, for the same set -e reason as
        # _node_install_cleanup() above -- an empty/unset $_LAST_SSH_PID
        # (no RUN/PUT in flight right now) is the common case, not an
        # edge case, and must not abort this handler under `set -e`.
        if [ -n "${_LAST_SSH_PID:-}" ]; then
            kill -TERM -- "-$_LAST_SSH_PID" 2>/dev/null || true
        fi

        # Best-effort remote cleanup, narrowly scoped to exactly what this
        # flow itself created (nothing else can be sharing
        # /opt/remnanode's compose project — it was `rm -rf`'d and
        # regenerated by this same invocation a few lines above). Issued
        # over a *fresh* SSH connection: killing the local ssh client
        # above stops *us* from waiting on it, it does not by itself
        # guarantee the remote command stopped, so this is a genuine
        # follow-up attempt, not a formality. Only attempted once SSH is
        # actually initialized — if interrupted before that point there is
        # nothing remote to clean up yet.
        if [ -n "${_SSH_IP:-}" ] && [ -n "${_SSH_USER:-}" ]; then
            RUN "cd /opt/remnanode 2>/dev/null && docker compose down 2>/dev/null; rm -rf /opt/remnanode" \
                >/dev/null 2>&1 || true
        fi

        _node_install_cleanup
        warn "Прервано (${_sig}) — локальные и (по возможности) удалённые артефакты удалены."

        # Do not report success (exit 0) merely because cleanup succeeded,
        # and do not invent a project-specific exit convention: reset the
        # trap to default and re-raise the same signal to ourselves. This
        # matches the *existing*, already-standard behavior of every other
        # unguarded operation in this tool (nothing else installs an INT
        # trap either, so Ctrl-C already just ends the process) — this
        # stage adds reliable cleanup in front of that, it does not
        # introduce a new "return to the menu" behavior nobody asked for.
        trap - INT TERM
        # $BASHPID, not $$: inside a subshell, $$ resolves to the PID of
        # the *top-level* shell that ultimately spawned it, not the
        # actual running process -- confirmed empirically this session
        # (`( echo $$; ) &` prints the *parent's* PID, `$BASHPID`/`$!`
        # give the real one). In this tool's normal, direct invocation
        # (server-manager.sh run as the single top-level process,
        # nothing here ever backgrounds or subshells this function) $$
        # and $BASHPID happen to coincide, so this was not visibly wrong
        # in the ordinary case -- but re-raising to $$ instead of the
        # actual current process is the wrong primitive on its own
        # merits, would misfire the moment this code is ever reached
        # from inside any subshell, and is exactly the class of "looks
        # right, is not explainable in terms of actual process behavior"
        # mistake this stage exists to avoid making elsewhere.
        kill -s "$_sig" "$BASHPID"
    }

    trap '_node_install_cleanup' RETURN
    trap '_node_install_signal_cleanup INT'  INT
    trap '_node_install_signal_cleanup TERM' TERM

    section "Вход в Panel API"
    local SUPERADMIN_USER SUPERADMIN_PASS
    ask SUPERADMIN_USER "Логин суперадмина Panel"
    stty -echo 2>/dev/null || true
    read -rp "  Пароль суперадмина Panel: " SUPERADMIN_PASS < /dev/tty
    stty echo 2>/dev/null || true
    echo ""

    info "Получение Node authentication secret..."
    local SECRET_KEY
    SECRET_KEY=$(panel_node_fetch_secret "$SUPERADMIN_USER" "$SUPERADMIN_PASS")
    if [ -z "$SECRET_KEY" ]; then
        warn "Не удалось авторизоваться / получить secret из Panel API. Проверьте логин/пароль."
        return 1
    fi
    ok "Secret получен"

    section "Данные ноды"
    ensure_sshpass
    ask_ssh_target || { warn "Ошибка ввода данных SSH"; return 1; }
    init_ssh_helpers full
    check_ssh_connection || return 1

    local SELFSTEAL_DOMAIN
    while true; do
        ask SELFSTEAL_DOMAIN "Selfsteal-домен этой ноды (node.example.com)"
        validate_domain "$SELFSTEAL_DOMAIN" && break || warn "Неверный формат"
    done

    local PANEL_IP _default_ip
    _default_ip="$(get_public_ip 2>/dev/null || echo "")"
    while true; do
        ask PANEL_IP "IP этой панели (для firewall-разрешения :2222 на ноде)" "$_default_ip"
        [[ "$PANEL_IP" =~ ^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$ ]] && break
        warn "Неверный формат IP"
    done

    echo ""
    remote_install_deps node || return 1

    # ── Locking down control port: только с PANEL_IP ────────────────
    if RUN "ufw allow from ${PANEL_IP} to any port 2222 proto tcp"; then
        ok "2222/tcp разрешён только с ${PANEL_IP}"
    else
        warn "Не удалось добавить firewall-правило для 2222/tcp — проверьте вручную на ${_SSH_IP}"
        return 1
    fi

    # ── Локальная генерация (staging на Panel-хосте) ───────────────
    info "Генерация docker-compose.yml и Caddyfile для ноды..."
    rm -rf /opt/remnanode 2>/dev/null
    panel_generate_node_compose "$SECRET_KEY" "$SELFSTEAL_DOMAIN"

    _selfsteal_staging="$(mktemp -d /tmp/sm_node_selfsteal_XXXXXX)"
    panel_generate_selfsteal_site "$_selfsteal_staging"

    # ── Перенос файлов на ноду ──────────────────────────────────────
    info "Копирование файлов на ${_SSH_IP}..."
    PUT /opt/remnanode/docker-compose.yml /opt/remnanode/Caddyfile \
        "${_SSH_USER}@${_SSH_IP}:/opt/remnanode/" || { warn "Не удалось скопировать compose/Caddyfile"; return 1; }
    RUN "mkdir -p /var/www/html" || true
    PUT "${_selfsteal_staging}/." \
        "${_SSH_USER}@${_SSH_IP}:/var/www/html/" || { warn "Не удалось скопировать selfsteal-контент"; return 1; }

    # ── Запуск ───────────────────────────────────────────────────────
    info "Запуск remnanode + Caddy на ${_SSH_IP}..."
    RUN "cd /opt/remnanode && docker compose up -d" || { warn "Не удалось запустить контейнеры на ноде"; return 1; }

    # ── Технические проверки ────────────────────────────────────────
    info "Проверка доступности control-порта 2222..."
    sleep 3
    if RUN "ss -tln 2>/dev/null | grep -q ':2222 '"; then
        ok "Нода слушает :2222"
    else
        warn "Не удалось подтвердить, что нода слушает :2222 — проверьте логи (docker compose logs) на ${_SSH_IP}"
    fi

    # ── Регистрация в Panel API ─────────────────────────────────────
    section "Регистрация в Panel"
    # Contract 2/3 (IO-02): проверяем propagated exit code panel_node_register(),
    # не emptiness stdout. `_reg_out` объявлена через `local` отдельной строкой
    # (не `local _reg_out=$(...)`), чтобы `!`/`if` видели реальный `$?` вызова,
    # а не `local`'а — тот самый local-masks-$? паттерн, которого требует
    # избегать contract 3. Работает корректно после fix'а contract 1
    # (panel_node_register больше не льёт UI-текст в stdout ни на одном из
    # своих explicit `return 1` путей — auth/keygen/config-profile/node
    # creation), поэтому stdout теперь либо чист, либо содержит "TOKEN UUID".
    local _reg_out TOKEN NODE_UUID
    if ! _reg_out=$(panel_node_register "$SUPERADMIN_USER" "$SUPERADMIN_PASS" "$SELFSTEAL_DOMAIN" "$_SSH_IP"); then
        warn "Регистрация в Panel API не удалась. Нода развёрнута, но не зарегистрирована."
        warn "Повторите регистрацию вручную через Panel UI или запустите операцию снова."
        return 1
    fi
    TOKEN="${_reg_out%% *}"
    NODE_UUID="${_reg_out##* }"

    # ── Health-check ─────────────────────────────────────────────────
    echo ""
    section "Проверка подключения"
    if panel_node_wait_connected "$TOKEN" "$NODE_UUID"; then
        echo ""
        ok "Remote Node развёрнута, зарегистрирована и подключена: ${_SSH_IP} (${SELFSTEAL_DOMAIN})"
        echo -e "  ${GRAY}Node UUID: ${NODE_UUID}${NC}"
    else
        echo ""
        warn "Remote Node развёрнута и зарегистрирована в Panel (uuid=${NODE_UUID}),"
        warn "но Panel пока не подтвердил подключение (isConnected != true)."
        warn "Нода НЕ считается полностью готовой. Проверьте:"
        warn "  · docker compose logs remnanode на ${_SSH_IP}"
        warn "  · что порт 2222 на ноде открыт для IP этой панели (${PANEL_IP})"
        warn "  · при необходимости удалите/пересоздайте ноду через Panel UI (uuid=${NODE_UUID})"
    fi
    echo ""
    read -rp "  Нажмите Enter чтобы продолжить..." < /dev/tty
}
